### ISSUE TITLE
Relicense with "LGPL v2.1 or later"

### ISSUE THREAD

**Issue by canesin** [jdherman/SALib#53]
Hi, I noticed that the project is using LGPL v3, this put many restrictions on it (for example other libraries with LGPL v2.1 and even GPLv2!). Please read the GnuTLS experience at: http://nmav.gnutls.org/2013/03/the-perils-of-lgplv3.html

It forces the libraries to migrate to GPL v3, look at the compatibility matrix: http://gplv3.fsf.org/dd3-faq

One very easy way to fix that is to license the software under "LGPLv2.1 or later" so the people can combine it with GPLv2 and LGPLv2.1 and also with GPLv3 and LGPLv3 code.

Best regards,
Fábio

**Comment by jdherman** [comment]
closed by #54
